
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from pathlib import Path
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / "assets" / "frame0"

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

window.geometry("675x750")
window.configure(bg = "#D2E2E2")


canvas = Canvas(
    window,
    bg = "#D2E2E2",
    height = 750,
    width = 675,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    337.0,
    375.0,
    image=image_image_1
)

canvas.create_text(
    51.0,
    32.0,
    anchor="nw",
    text="GPA CALCULATOR",
    fill="#03045E",
    font=("Rubik Bold", 36 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=278.0,
    y=555.0,
    width=120.0,
    height=30.0
)

canvas.create_rectangle(
    51.0,
    105.0,
    623.0,
    525.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    98.0,
    184.0,
    anchor="nw",
    text="Course Name",
    fill="#046865",
    font=("Rubik Bold", 18 * -1)
)

canvas.create_text(
    308.0,
    184.0,
    anchor="nw",
    text="Grade",
    fill="#046865",
    font=("Rubik Bold", 18 * -1)
)

canvas.create_text(
    440.0,
    184.0,
    anchor="nw",
    text="Credits",
    fill="#046865",
    font=("Rubik Bold", 18 * -1)
)

canvas.create_rectangle(
    98.0,
    219.0,
    273.0,
    254.0,
    fill="#D2E1E1",
    outline="")

canvas.create_rectangle(
    308.0,
    219.0,
    405.0,
    254.0,
    fill="#D2E1E1",
    outline="")

canvas.create_rectangle(
    440.0,
    219.0,
    537.0,
    254.0,
    fill="#D2E1E1",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=560.0,
    y=226.0,
    width=17.0,
    height=17.433963775634766
)

canvas.create_rectangle(
    98.0,
    268.0,
    273.0,
    303.0,
    fill="#D2E1E1",
    outline="")

canvas.create_rectangle(
    308.0,
    268.0,
    405.0,
    303.0,
    fill="#D2E1E1",
    outline="")

canvas.create_rectangle(
    440.0,
    268.0,
    537.0,
    303.0,
    fill="#D2E1E1",
    outline="")

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=560.0,
    y=275.3914794921875,
    width=17.0,
    height=17.433963775634766
)

canvas.create_rectangle(
    98.0,
    317.0,
    273.0,
    352.0,
    fill="#D2E1E1",
    outline="")

canvas.create_rectangle(
    308.0,
    317.0,
    405.0,
    352.0,
    fill="#D2E1E1",
    outline="")

canvas.create_rectangle(
    440.0,
    317.0,
    537.0,
    352.0,
    fill="#D2E1E1",
    outline="")

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=560.0,
    y=326.7829895019531,
    width=17.0,
    height=17.433963775634766
)

canvas.create_rectangle(
    98.0,
    366.0,
    273.0,
    401.0,
    fill="#D2E1E1",
    outline="")

canvas.create_rectangle(
    308.0,
    366.0,
    405.0,
    401.0,
    fill="#D2E1E1",
    outline="")

canvas.create_rectangle(
    440.0,
    366.0,
    537.0,
    401.0,
    fill="#D2E1E1",
    outline="")

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=560.0,
    y=377.1745300292969,
    width=17.0,
    height=17.433963775634766
)

canvas.create_rectangle(
    98.0,
    415.0,
    273.0,
    450.0,
    fill="#D2E1E1",
    outline="")

canvas.create_rectangle(
    308.0,
    415.0,
    405.0,
    450.0,
    fill="#D2E1E1",
    outline="")

canvas.create_rectangle(
    440.0,
    415.0,
    537.0,
    450.0,
    fill="#D2E1E1",
    outline="")

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=560.0,
    y=424.5660400390625,
    width=17.0,
    height=17.433963775634766
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=285.0,
    y=474.0,
    width=105.0,
    height=17.0
)

canvas.create_rectangle(
    51.0,
    630.0,
    623.0,
    700.0,
    fill="#046865",
    outline="")

canvas.create_text(
    513.0,
    651.0,
    anchor="nw",
    text="0.00",
    fill="#F2F7F7",
    font=("Rubik Medium", 24 * -1)
)

canvas.create_text(
    107.0,
    651.0,
    anchor="nw",
    text="Semester GPA",
    fill="#F2F7F7",
    font=("Rubik Medium", 24 * -1)
)
window.resizable(False, False)
window.mainloop()
